from . import hr_attendance
from . import hr_employee
from . import res_config_settings
from . import res_users
from . import resource
from . import resource_plan
from . import resource_plan_resource
from . import resource_plan_role
from . import resource_planning
from . import resource_role 
from . import resource_shift 
from . import resource_slot
from . import resource_week_template
from . import resource_week_template_line
from . import resource_week_template_shift
